
package net.tuto2.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSConcat", targetNamespace = "http://david.bromberg.fr/service/concat")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WSConcat {


    /**
     * 
     * @param n1
     * @param n2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    public int concat(
        @WebParam(name = "n1", partName = "n1")
        int n1,
        @WebParam(name = "n2", partName = "n2")
        int n2);

}
